name: Caliper Benchmarks
version: "2.0.0"
# mutual-tls: false

caliper:
  blockchain: fabric

info:
  Version: 2.5.9
  Size: 2 Orgs with 2 Peer
  Orderer: Raft
  Distribution: Single Host
  StateDB: CouchDB
 
channels:
  - channelName: mychannel
    # the chaincodeIDs of all the fabric chaincodes in caliper-benchmarks
    contracts:
    - id: basic

organizations:
  - mspid: Org1MSP
    # Identities come from cryptogen created material for test-network
    identities:
      certificates:
      - name: 'User1'
        clientPrivateKey:
          path: /home/uw-mxl31926tn/hlf/fabric/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/priv_sk
        clientSignedCert:
          path: /home/uw-mxl31926tn/hlf/fabric/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem
    connectionProfile:
      path: /home/uw-mxl31926tn/hlf/fabric/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/connection-org1.json
      discover: true
